### ISSUE TITLE
Get stream logic doesn't take into account bot reconnects

### ISSUE THREAD

**Issue by dl-eric** [dl-eric/naccs-bot#5]
Occasionally, the bot will reconnect to the Discord server due to whatever reason. This triggers an exception where it will attempt to run the Stream task again (on_ready being called again). It will also clear the stream channel unnecessarily.

**Comment by sphhax** [comment]
Is this resolved? I see the code changes in 57fee1a

**Comment by dl-eric** [comment]
Yep
